spring:
  profiles:
    active: dev

server:
  forward-headers-strategy: native

springdoc:
  swagger-ui:
    path: /doc/swagger-ui
    defaultModelsExpandDepth: -1

secrets:
  spotify_api:
    id: ${SPOTIFY_API_CLIENT_ID}
    secret: ${SPOTIFY_API_CLIENT_SECRET}
  tidal_api:
    id: ${TIDAL_API_CLIENT_ID}
    secret: ${TIDAL_API_CLIENT_SECRET}

webdriver:
  host: ${WEBDRIVER_HOST:localhost}
  port: ${WEBDRIVER_PORT:4444}