logging:
  level:
    root: DEBUG
    br.com.arpeggio.api: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"

server:
  port: ${PORT}
  address: 0.0.0.0
  forward-headers-strategy: framework