springdoc:
  swagger-ui:
    path: /doc/swagger-ui

secrets:
  spotify_api:
    id: ${SPOTIFY_API_CLIENT_ID}
    secret: ${SPOTIFY_API_CLIENT_SECRET}
  tidal_api:
    id: ${TIDAL_API_CLIENT_ID}
    secret: ${TIDAL_API_CLIENT_SECRET}

chrome:
  url: ${CHROME_URL:http://localhost}
  port: ${CHROME_PORT:4444}

spring:
  webflux:
    cors:
      allowed-origins: https://arpejo.up.railway.app/doc/swagger-ui/index.html
