springdoc:
  swagger-ui:
    path: /doc/swagger-ui
    defaultModelsExpandDepth: -1

secrets:
  spotify_api:
    id: ${SPOTIFY_API_CLIENT_ID}
    secret: ${SPOTIFY_API_CLIENT_SECRET}
  tidal_api:
    id: ${TIDAL_API_CLIENT_ID}
    secret: ${TIDAL_API_CLIENT_SECRET}

chrome:
  url: ${CHROME_HOST}
  port: ${CHROME_PORT}
